"""Loading the tile art into Pyxel's image banks.

Pyxel can load PNGs straight into an image bank at runtime
(`pyxel.images[n].load(x, y, path)`), so there is no atlas to build and no
image library dependency.

Everything here is **ours**: the terrain drawn in `art/terrain/`, the glyphs and
the logo written out by `tools/tile_gen.py` and the bike rastered from its model
by `tools/sprite_gen.py`, committed under `art/`, and **required**: a missing tile is a fatal error. A second,
optional collection loaded only when present is what "required" stops meaning,
and it brings a family of skips with it.

There is a second place a tile may come from, and it is still ours:
`art/hand/<name>.png` is a **drawing** rather than a derivation, and it wins over
the generated tile of the same name. Art has only ever been addressed by name, so
the game neither knows nor cares which of the two it got; delete the file and the
derived one comes back. `art/tiles/` and `art/moto/` stay a cache with a proof --
`tools/tile_gen.py --check` reads those directories and a hand-drawn file never
touches them -- and `tools/art_check.py` is what a drawing answers to instead.
"""

import difflib
import os

import pyxel

from game.constants import CELL, TILE
from maps import read

BANK = 0
_BANK_COLS = pyxel.IMAGE_SIZE // CELL

# The terrain, which is drawn on TILE rather than CELL and so has a bank
# of its own: 1024 slots of 8x8, and a lookup of its own beside `uv`. Every
# `blt` that reads BANK reads it in CELL steps, and a tile of eight among them
# would be a tile nobody could address.
TERRAIN_BANK = 1
_TERRAIN_COLS = pyxel.IMAGE_SIZE // TILE

_ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
ART_DIR = os.path.join(_ROOT, "art", "tiles")
MOTO_DIR = os.path.join(_ROOT, "art", "moto")

# Where a drawing goes, and **it is committed** -- which is the guard rather than
# a detail: art that cannot be committed cannot go in here.
HAND_DIR = os.path.join(_ROOT, "art", "hand")

# Every tile in `art/tiles/`, generated by `tools/tile_gen.py` and committed --
# and the list of names a drawing in `art/hand/` may answer to. A file there
# whose stem is not on this list or in `BIKE_TILES` is refused by `load_all`,
# because nothing would ever load it.
#
# Order decides the slot layout in the bank, but only by accident: nothing
# anywhere addresses a tile by slot, and `uv(name)` is the only lookup there has
# ever been. That is what made a whole collection removable without a diff
# anywhere else -- and this list was ninety-five names before the catalogue went.
#
# Every glyph the generator draws on the `CELL` grid. The terrain is a map's,
# on a grid of eight: `TERRAIN_TILES`, in a bank of its own.
GLYPH_TILES = [
    # The HUD's own counter, which is a bomb rather than an "N": the crate on the
    # course says *there is one here* and this says *you have one*, which are two
    # jobs and two pictures. See `tools/tile_gen.GLYPHS`.
    "nitro",
    # The pickups as they are drawn *on the course*, which is not the same
    # picture as the HUD icon. Three of them, one per kind the game credits --
    # and `item_jet` has no letter any map can write, so it is drawn for a crate
    # only a `Course` built in a test can place.
    "item_nitro",
    "item_time",
    "item_jet",
    # What a secret taken leaves: the J is its crate, a mini-maniac this one --
    # and the mini-maniac itself, eight pixels square.
    "item_mini",
    "mini",
    # The rock, which is neither a piece nor a pickup: a thing at a position that
    # is in the way. Hand-authored like the crates, because there is no curve it
    # could be a function of.
    "rock",
]

# The title screen's own furniture, a list of its own rather than sixteen more
# names in `GLYPH_TILES` because it is one picture cut up rather than sixteen.
#
# It is also the answer to a question `tools/art_check.py` has to ask -- which of
# the kinds of tile is this one -- and a list answers it as data, where a test on
# the name would be a convention nobody declared. Sixteen cells of one 128x32
# picture, authored whole in `tools/tile_gen.BANNERS` and cut up by
# `slice_banner`; they live in `art/tiles/` with everything else the generator
# writes, and `art/hand/logo_31.png` wins over one exactly as it would over a
# glyph.
SCREEN_TILES = ["logo_%d%d" % (col, row) for col in range(8) for row in range(2)]

# The 32 rotations of the bike, generated from the model in `tools/sprite_gen.py`
# and the only bike this game has.
BIKE_TILES = ["bike%02d" % n for n in range(32)]

# The crash: the bike on its back, and five poses of the rider who is no longer
# on it. A group of their own rather than six more `BIKE_TILES`, because that
# list means "the 32 rotations" -- appending to it would have `tools/art_check.py` describe the wreck as bike pose 32 of 32.
# Same directory, though: `tools/sprite_gen.py` writes them from the same model,
# so they are covered by the same `--check`.
CRASH_TILES = [
    "wreck",
    "rider_lying",
    "rider_rising",
    "rider_walk_a",
    "rider_walk_b",
    "rider_lifting",
]

# (names, directory). Two of the four point at `art/tiles/`, which is the one
# directory `tools/tile_gen.py` writes.
_GROUPS = (
    (GLYPH_TILES, ART_DIR),
    (SCREEN_TILES, ART_DIR),
    (BIKE_TILES, MOTO_DIR),
    (CRASH_TILES, MOTO_DIR),
)

_uv: dict[str, tuple[int, int]] = {}
_hand: set[str] = set()


def uv(name: str) -> tuple[int, int]:
    """Bank coordinates of a tile, by name. Raises if assets were not loaded."""
    return _uv[name]


def names() -> list[str]:
    return list(_uv)


def hand_drawn() -> set[str]:
    """Names loaded from `art/hand/` rather than from the generator.

    What the three identity tests exclude from their loops -- they are claims
    about what the *generator* put in the bank, and a drawing is by definition
    not that. Excluded from a loop and never `pytest.skip`ped: the suite says it
    has no skips, and that must go on being true the first time somebody draws.
    """
    return set(_hand)


TERRAIN_DIR = os.path.join(_ROOT, "art", "terrain")

# Every terrain tile a map of this game's own is drawn out of, loaded into
# TERRAIN_BANK from `art/terrain/` at TILE.
#
# **The names come from `maps/tiles.json`**, which is where each one also says
# what it collides as: one list, so a tile that rides cannot be a tile that
# nothing draws, and the other way about. Read here at import, because the bank
# is loaded once and the list is a fact about the disk.
TERRAIN_TILES: list[str] = list(read.tile_names())

_terrain_uv: dict[str, tuple[int, int]] = {}
_terrain_hand: set[str] = set()


def terrain_uv(name: str) -> tuple[int, int]:
    """Coordinates of a terrain tile in TERRAIN_BANK, by name."""
    return _terrain_uv[name]


def terrain_names() -> list[str]:
    """Every terrain tile loaded into TERRAIN_BANK, in the order it was loaded."""
    return list(_terrain_uv)


def hand_drawn_terrain() -> set[str]:
    """Terrain names loaded from `art/hand/` rather than from `art/terrain/`."""
    return set(_terrain_hand)


def read_terrain(name: str) -> tuple[int, ...]:
    """A terrain tile's pixels as TILE*TILE palette indices, row-major."""
    u, v = _terrain_uv[name]
    image = pyxel.images[TERRAIN_BANK]
    return tuple(image.pget(u + x, v + y) for y in range(TILE) for x in range(TILE))


def _load_terrain() -> None:
    """The terrain tiles into TERRAIN_BANK, a drawing winning by name."""
    _terrain_uv.clear()
    _terrain_hand.clear()
    if len(TERRAIN_TILES) > _TERRAIN_COLS * _TERRAIN_COLS:
        raise ValueError("bank %d holds %d tiles and %d are named"
                         % (TERRAIN_BANK, _TERRAIN_COLS * _TERRAIN_COLS, len(TERRAIN_TILES)))
    for slot, name in enumerate(TERRAIN_TILES):
        path = os.path.join(TERRAIN_DIR, name + ".png")
        drawn = os.path.join(HAND_DIR, name + ".png")
        if os.path.exists(drawn):
            path = drawn
            _terrain_hand.add(name)
        u = (slot % _TERRAIN_COLS) * TILE
        v = (slot // _TERRAIN_COLS) * TILE
        pyxel.images[TERRAIN_BANK].load(u, v, path)
        _terrain_uv[name] = (u, v)


def _stray_drawings() -> list[tuple[str, str | None]]:
    """Files in `art/hand/` that no name loads. Returns `[(filename, guess)]`."""
    if not os.path.isdir(HAND_DIR):
        return []
    known = {name for group, _ in _GROUPS for name in group} | set(TERRAIN_TILES)
    stray: list[tuple[str, str | None]] = []
    for filename in sorted(os.listdir(HAND_DIR)):
        if not filename.endswith(".png"):
            continue
        stem = filename[:-4]
        if stem in known:
            continue
        near = difflib.get_close_matches(stem, sorted(known), n=1)
        stray.append((filename, near[0] if near else None))
    return stray


def load_all() -> dict[str, tuple[int, int]]:
    """Load every tile into BANK. Palette must already be applied.

    A missing tile raises, because the game cannot draw without it. So does a
    **stray** drawing -- a file in `art/hand/` whose stem is not a tile name --
    which is the one failure this mechanism can have with no other symptom. Nothing loads such a file, so today it would be a typo that
    draws nothing, reported by nobody, in a directory whose whole purpose is that
    what you put in it appears on the screen.
    """
    _uv.clear()
    _hand.clear()
    stray = _stray_drawings()
    if stray:
        raise ValueError(
            "art/hand/ holds %d file(s) no tile is named after:\n%s"
            % (
                len(stray),
                "\n".join(
                    "  %s%s" % (name, "" if guess is None else "  (did you mean %s.png?)" % guess)
                    for name, guess in stray
                ),
            )
        )
    slot = 0
    for group, directory in _GROUPS:
        for name in group:
            path = os.path.join(directory, name + ".png")
            drawn = os.path.join(HAND_DIR, name + ".png")
            if os.path.exists(drawn):
                path = drawn
                _hand.add(name)
            if slot >= _BANK_COLS * _BANK_COLS:
                # Never hit, and it went unchecked until a batch of sixteen
                # names arrived at once:
                # past the last slot `v` simply runs off the bottom of the bank
                # and the tile is loaded nowhere, which draws as sky.
                raise ValueError(
                    "bank %d holds %d tiles and this is the %dth"
                    % (BANK, _BANK_COLS * _BANK_COLS, slot + 1)
                )
            u = (slot % _BANK_COLS) * CELL
            v = (slot // _BANK_COLS) * CELL
            pyxel.images[BANK].load(u, v, path)
            _uv[name] = (u, v)
            slot += 1
    _load_terrain()
    return dict(_uv)


def read_tile(name: str) -> tuple[int, ...]:
    """Tile pixels as a tuple of CELL*CELL palette indices, row-major."""
    u, v = _uv[name]
    image = pyxel.images[BANK]
    return tuple(image.pget(u + x, v + y) for y in range(CELL) for x in range(CELL))
